/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flexmark.mendix;

import org.junit.Assert;
import org.junit.Test;

public class MarkdownToHTMLConverterTest {

    @Test public void basicTest() {
        MarkdownToHTMLConverter converter = MarkdownToHTMLConverter.createConverter();
        String expectedHTML = "<p>This is <em>Sparta</em></p>\n";
        String markdown = "This is *Sparta*";
        Assert.assertEquals(expectedHTML, converter.convert(markdown));
    }

}
