/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flexmark.mendix;

import com.vladsch.flexmark.html.HtmlRenderer;
import com.vladsch.flexmark.parser.Parser;
import com.vladsch.flexmark.util.ast.Node;
import com.vladsch.flexmark.util.data.MutableDataSet;

class FlexmarkConverter implements MarkdownToHTMLConverter {

    @Override
    public String convert(String markdown) {
        MutableDataSet options = new MutableDataSet();
        Parser parser = Parser.builder(options).build();
        HtmlRenderer renderer = HtmlRenderer.builder(options).build();
        Node document = parser.parse(markdown);
        String html = renderer.render(document);
        return html;
    }
}

public interface MarkdownToHTMLConverter {
    String convert(String markdown);

    static MarkdownToHTMLConverter createConverter() {
        return new FlexmarkConverter();
    }
}
